alias be='bundle exec'
alias bo='bundle open'
alias cp='cp --reflink=auto'
alias dc='docker-compose'
alias g='git'
alias la='ll -a'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias open='xdg-open'
alias yr='yarn run'
