alias be='bundle exec'
alias bo='bundle open'
alias dc='docker-compose'
alias g='git'
alias la='ll -a'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias op='xdg-open'
alias sc='systemctl'
alias scu='systemctl --user'
alias tf='terraform'
alias yr='yarn run'
