alias grep='grep --color=auto'
alias ip='ip -color=auto'

alias be='bundle exec'
alias bo='bundle open'
alias c='cargo'
alias dc='docker compose'
alias de='direnv edit'
alias g='git'
alias la='ll -a'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias open='xdg-open'
alias tf='terraform'
alias y='yarn'
