source $VIMRUNTIME/defaults.vim

call plug#begin()

Plug 'ConradIrwin/vim-bracketed-paste'
Plug 'adelarsq/vim-matchit'
Plug 'airblade/vim-gitgutter'
Plug 'csexton/trailertrash.vim'
Plug 'dhruvasagar/vim-table-mode'
Plug 'docunext/closetag.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'ervandew/supertab'
Plug 'fatih/vim-go'
Plug 'joker1007/vim-ruby-heredoc-syntax'
Plug 'junegunn/vim-easy-align'
Plug 'kana/vim-textobj-indent'
Plug 'kana/vim-textobj-user'
Plug 'machakann/vim-swap'
Plug 'morhetz/gruvbox'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'qpkorr/vim-bufkill'
Plug 'rhysd/vim-textobj-ruby'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'

call plug#end()

set background=dark
set breakindent
set cursorline
set directory-=.
set expandtab
set hidden
set lazyredraw
set list
set matchtime=1
set modeline
set number
set showmatch
set tabstop=4
set termguicolors
set virtualedit=block
set wildmode=list:longest,list:full

if executable('rg')
  set grepprg=rg\ --vimgrep\ --no-heading
  set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

let g:go_fmt_command = 'goimports'
let g:gruvbox_italic = 1
let g:netrw_liststyle = 3
let g:table_mode_corner = '|'

let g:terminal_ansi_colors = [
  \ '#073642',
  \ '#dc322f',
  \ '#859900',
  \ '#b58900',
  \ '#268bd2',
  \ '#d33682',
  \ '#2aa198',
  \ '#eee8d5',
  \ '#002b36',
  \ '#cb4b16',
  \ '#586e75',
  \ '#657b83',
  \ '#839496',
  \ '#6c71c4',
  \ '#93a1a1',
  \ '#fdf6e3',
  \ ]

let g:coc_global_extensions = [
  \ 'coc-css',
  \ 'coc-ember',
  \ 'coc-eslint',
  \ 'coc-html',
  \ 'coc-json',
  \ 'coc-solargraph',
  \ 'coc-stylelint',
  \ 'coc-tsserver',
  \ 'coc-yaml',
  \ ]

colorscheme gruvbox

cmap <C-x> <C-r>=expand('%:p:h')<CR>/

xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

augroup vimrc
  autocmd!

  autocmd QuickFixCmdPost make,grep,grepadd,vimgrep,vimgrepadd,Ggrep cwin
  autocmd QuickFixCmdPost lmake,lgrep,lgrepadd,lvimgrep,lvimgrepadd lwin

  autocmd FileType * setlocal formatoptions-=r formatoptions-=r
augroup END
