source /etc/profile.d/vte-*.sh
source ~/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle mollifier/anyframe
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

setopt prompt_subst
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_no_store
setopt share_history
setopt extended_history
setopt extended_glob

autoload -Uz colors && colors
autoload -Uz compinit && compinit
autoload -Uz bashcompinit && bashcompinit
autoload -Uz vcs_info
autoload -Uz zmv

PROMPT=$'%(!.%{$fg_bold[red]%}.%{$fg_bold[green]%}%n@)%m %{$fg_bold[blue]%}%(!.%1~.%~)%{$reset_color%} $(git_prompt_info)\n%{$fg_bold[blue]%}$%{$reset_color%} '
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}("

export PATH=$HOME/bin:$HOME/go/bin:$HOME/.yarn/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH:$HOME/.heroku/bin


export GO111MODULES=on
export GOPATH=$HOME/go:$HOME
export PGUSER=postgres
export RUBY_CFLAGS='-O3 -pipe -march=native'
export RUBY_MAKE_OPTS='-j4 -l4'
export UNZIP='-O cp932'

source $HOME/.asdf/asdf.sh
source $HOME/.asdf/completions/asdf.bash

for i in ~/.cache/heroku/autocomplete/zsh_setup ~/.google-cloud-sdk/{path,completion}.zsh.inc ~/.travis/travis.sh; do
  [ -f $i ] && source $i
done

eval "$(direnv hook zsh)"

alias be='bundle exec'
alias bo='bundle open'
alias dc='docker-compose'
alias g='git'
alias open='xdg-open'
alias pwgen='pwgen --secure --num-passwords=1'
alias yr='yarn run'

function ember() {
  if [ -f yarn.lock ]; then
    yarn run ember $@
  else
    npx ember $@
  fi
}

bindkey '^g' anyframe-widget-cd-ghq-repository
bindkey '^r' history-incremental-search-backward
