shell = 'zsh'

[plugins]

[plugins.anyframe]
github = 'mollifier/anyframe'

[plugins.fzf]
local = '/usr/share/fzf'
use = ['key-bindings.zsh']

[plugins._heroku]
local = '~/.cache/heroku'
use = ['autocomplete/zsh_setup']

[plugins.ohmyzsh]
github = 'ohmyzsh/ohmyzsh'
use = ['lib/{functions,git,history,termsupport,theme-and-appearance}.zsh', 'themes/gentoo.zsh-theme']

[plugins.zsh-abbr]
github = 'olets/zsh-abbr'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
