#!/bin/sh

set -e

rcup -K zsh/.zshrc

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

zsnap=$XDG_DATA_HOME/znap/zsh-snap

if [ ! -e $zsnap ]; then
  git clone  https://github.com/marlonrichert/zsh-snap.git $zsnap
fi

vim_plug=$XDG_DATA_HOME/nvim/site/autoload/plug.vim

if [ ! -e $vim_plug ]; then
  curl --fail --location --output $vim_plug --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim +PlugInstall +qa
fi

heroku=$XDG_DATA_HOME/heroku

if [ ! -e $heroku ]; then
  curl --fail --location https://cli-assets.heroku.com/heroku-linux-x64.tar.gz | tar xvzf - --strip-components=1 --one-top-level=$heroku
  $heroku/bin/heroku autocomplete
fi
