[tools]
flyctl = "latest"
gcloud = "latest"
glab = { version = "latest", exe = "glab" }
node = "lts"
ruby = "4.0.4"
rust = "latest"
sentry = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]

[settings.ruby]
compile = true
