[tools]
flyctl = "latest"
gcloud = "latest"
node = "lts"
ruby = "4.0.2"
rust = "latest"
sentry = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]

[settings.ruby]
compile = true
