[tools]
claude-code = "latest"
flyctl = "latest"
node = "lts"
pnpm = "11"
ruby = "4.0.6"
rust = "latest"
usage = "latest"

"github:ankitpokhrel/jira-cli" = "latest"
"github:k1LoW/mo" = "latest"
"github:rbspy/rbspy" = { version = "latest", rename_exe = "rbspy" }
"npm:confluence-cli" = "latest"
"npm:heroku" = "latest"
"npm:ntn" = "latest"
"npm:sentry" = "latest"
"npm:typescript-language-server" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]

[settings.ruby]
compile = true

[dotfiles."~"]
source =  "~/Code/github.com/ursm/dotfiles"
mode = "symlink-each"
manifest = "git"
