[tool_alias]
logcli = "github:grafana/loki"

[tools]
claude-code = "latest"
node = "lts"
ruby = "4.0.6"
rust = "latest"
usage = "latest"

"github:ankitpokhrel/jira-cli" = "latest"
"github:k1LoW/mo" = "latest"
"github:rbspy/rbspy" = { version = "latest", rename_exe = "rbspy" }
"github:superfly/flyctl" = { version = "latest", postinstall = 'ln -sf flyctl "$MISE_TOOL_INSTALL_PATH/fly"' }
"logcli" = { version = "latest", rename_exe = "logcli", asset_pattern = "logcli-linux-amd64.zip" }
"npm:confluence-cli" = "latest"
"npm:heroku" = "latest"
"npm:ntn" = "latest"
"npm:pnpm" = "11"
"npm:sentry" = "latest"
"npm:typescript-language-server" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]

[settings.ruby]
compile = true

[dotfiles."~"]
source =  "~/Code/github.com/ursm/dotfiles"
mode = "symlink-each"
manifest = "git"
